/**
 * WooCommerce CSV Export Template
 * Generates CSV files compatible with WooCommerce product import
 * Reference: https://woocommerce.com/document/product-csv-importer-exporter/
 */

(function() {
  "use strict";

  const WOO_COLUMNS = [
    { key: 'ID', header: 'ID' },
    { key: 'Type', header: 'Type' },
    { key: 'SKU', header: 'SKU' },
    { key: 'Name', header: 'Name' },
    { key: 'Published', header: 'Published' },
    { key: 'IsFeatured', header: 'Is featured?' },
    { key: 'VisibilityInCatalog', header: 'Visibility in catalog' },
    { key: 'ShortDescription', header: 'Short description' },
    { key: 'Description', header: 'Description' },
    { key: 'SalePrice', header: 'Sale price' },
    { key: 'RegularPrice', header: 'Regular price' },
    { key: 'Categories', header: 'Categories' },
    { key: 'Tags', header: 'Tags' },
    { key: 'Images', header: 'Images' },
    { key: 'Weight', header: 'Weight (kg)' },
    { key: 'StockStatus', header: 'In stock?' },
    { key: 'Stock', header: 'Stock' },
    { key: 'ManageStock', header: 'Backorders allowed?' },
    { key: 'Attribute1Name', header: 'Attribute 1 name' },
    { key: 'Attribute1Values', header: 'Attribute 1 value(s)' },
    { key: 'Attribute1Visible', header: 'Attribute 1 visible' },
    { key: 'Attribute1Global', header: 'Attribute 1 global' },
    { key: 'Attribute2Name', header: 'Attribute 2 name' },
    { key: 'Attribute2Values', header: 'Attribute 2 value(s)' },
    { key: 'Attribute2Visible', header: 'Attribute 2 visible' },
    { key: 'Attribute2Global', header: 'Attribute 2 global' },
    { key: 'MetaTitle', header: 'Meta: _yoast_wpseo_title' },
    { key: 'MetaDescription', header: 'Meta: _yoast_wpseo_metadesc' }
  ];

  function mapProduct(product, settings) {
    const images = (product.images || '').split(/[,;|]+/).map(s => s.trim()).filter(s => s.startsWith('http'));

    // Parse variants
    let variants = [];
    try {
      if (product.variants) {
        variants = typeof product.variants === 'string' ? JSON.parse(product.variants) : product.variants;
      }
    } catch (e) {}

    // Group variants by type
    const variantGroups = {};
    if (Array.isArray(variants)) {
      variants.forEach(v => {
        const type = v.type || 'Option';
        if (!variantGroups[type]) variantGroups[type] = [];
        variantGroups[type].push(v.name || v.value || '');
      });
    }

    const groupEntries = Object.entries(variantGroups);

    // WooCommerce categories use " > " for hierarchy
    const category = (product.category || '')
      .replace(/\/\/\//g, ' > ')
      .replace(/\s*>\s*/g, ' > ');

    const hasStock = product.quantity && parseInt(product.quantity) > 0;
    const regularPrice = product.list_price || product.price || '0.00';
    const salePrice = product.list_price ? product.price : '';

    return {
      ID: '',  // Auto-generated by WooCommerce
      Type: groupEntries.length > 0 ? 'variable' : 'simple',
      SKU: product.product_code || product.sku || '',
      Name: product.product_name || product.title || '',
      Published: product.status === 'A' || product.status === 'active' ? '1' : '0',
      IsFeatured: '0',
      VisibilityInCatalog: 'visible',
      ShortDescription: product.short_description || '',
      Description: product.description || '',
      SalePrice: salePrice,
      RegularPrice: regularPrice,
      Categories: category,
      Tags: product.meta_keywords || '',
      Images: images.join(', '),
      Weight: product.weight || '',
      StockStatus: hasStock ? '1' : '0',
      Stock: product.quantity || '',
      ManageStock: '0',
      Attribute1Name: groupEntries[0] ? groupEntries[0][0] : '',
      Attribute1Values: groupEntries[0] ? groupEntries[0][1].join(', ') : '',
      Attribute1Visible: groupEntries[0] ? '1' : '',
      Attribute1Global: groupEntries[0] ? '1' : '',
      Attribute2Name: groupEntries[1] ? groupEntries[1][0] : '',
      Attribute2Values: groupEntries[1] ? groupEntries[1][1].join(', ') : '',
      Attribute2Visible: groupEntries[1] ? '1' : '',
      Attribute2Global: groupEntries[1] ? '1' : '',
      MetaTitle: (product.product_name || product.title || '').substring(0, 70),
      MetaDescription: product.meta_description || (product.short_description || '').substring(0, 320)
    };
  }

  function toCSV(products, settings) {
    return CartTemplateRegistry.buildCSV(WOO_COLUMNS, products);
  }

  // Register with the template registry
  if (typeof CartTemplateRegistry !== 'undefined') {
    CartTemplateRegistry.register({
      id: 'woocommerce',
      name: 'WooCommerce',
      version: 'CSV',
      supportsXML: false,
      fields: WOO_COLUMNS.map(c => ({ key: c.key, label: c.header })),
      mapProduct: mapProduct,
      toCSV: toCSV
    });
  }
})();